### ISSUE TITLE
Error building for ios

### ISSUE THREAD

**Issue by amitkot** [mertguner/sound_generator#7]
I received this error while building for ios emulator:

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/amit/.pub-cache/hosted/pub.dartlang.org/sound_generator-0.0.5/ios/Classes/SwiftSoundGeneratorPlugin.swift:11:19: error: cannot find type 'AKOscillator' in scope
      var oscillator: AKOscillator = AKOscillator();
                      ^~~~~~~~~~~~
    /Users/amit/.pub-cache/hosted/pub.dartlang.org/sound_generator-0.0.5/ios/Classes/SwiftSoundGeneratorPlugin.swift:12:14: error: cannot find type 'AKMixer' in scope
      var mixer: AKMixer?;
                 ^~~~~~~
    /Users/amit/.pub-cache/hosted/pub.dartlang.org/sound_generator-0.0.5/ios/Classes/SwiftSoundGeneratorPlugin.swift:20:18: error: cannot find 'AKMixer' in scope
        self.mixer = AKMixer(self.oscillator)
                     ^~~~~~~
    /Users/amit/.pub-cache/hosted/pub.dartlang.org/sound_generator-0.0.5/ios/Classes/SwiftSoundGeneratorPlugin.swift:22:5: error: cannot find 'AKManager' in scope
        AKManager.output = self.mixer!
        ^~~~~~~~~
    /Users/amit/.pub-cache/hosted/pub.dartlang.org/sound_generator-0.0.5/ios/Classes/SwiftSoundGeneratorPlugin.swift:23:10: error: cannot find 'AKManager' in scope
        try! AKManager.start()
             ^~~~~~~~~

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

```

**Comment by leidig54** [comment]
Not sure if @ryanheise has a permanent solution for this, but I fixed it by adding 

`pod 'AudioKit', '4.11.2'`

to my podfile.

**Comment by mertguner** [comment]
build with 0.0.8 version
