### ISSUE TITLE
Error building with Flutter 3.29.0

### ISSUE THREAD

**Issue by gbellini79** [mertguner/sound_generator#30]
After upgrading Flutter to 3.29.0 I receive an error while building with ```flutter build apk``` on Windows.
```
C:\Users\giaco\AppData\Local\Pub\Cache\hosted\pub.dev\sound_generator-0.0.13\android\src\main\java\io\github\mertguner\sound_generator\SoundGeneratorPlugin.java:11: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
C:\Users\giaco\AppData\Local\Pub\Cache\hosted\pub.dev\sound_generator-0.0.13\android\src\main\java\io\github\mertguner\sound_generator\SoundGeneratorPlugin.java:43: error: cannot find symbol
  public static void registerWith(Registrar registrar) {
                                  ^
  symbol:   class Registrar
  location: class SoundGeneratorPlugin
Note: C:\Users\giaco\AppData\Local\Pub\Cache\hosted\pub.dev\sound_generator-0.0.13\android\src\main\java\io\github\mertguner\sound_generator\SoundGeneratorPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sound_generator:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 2s
```

Commenting those two sections in SoundGeneratorPlugin.java it builds and works correctly.

Could this be related to the deprecation of those API in the latest SDK?

Thank you

**Comment by Sahad2701** [comment]
If you're facing build issues with `sound_generator` due to deprecated `registerWith` usage like this:

```
cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
```

This is a temporary fix that updates the plugin to support modern Flutter (removes V1 embedding):   https://github.com/mertguner/sound_generator/pull/34/commits/08b7c04849879718d1d1eed2d72f08b85de61130

You can apply this fix by pointing to the patched version in your `pubspec.yaml`:

```yaml
sound_generator:
  git:
    url: https://github.com/mertguner/sound_generator.git
    ref: 08b7c04849879718d1d1eed2d72f08b85de61130
```

Then run:

```bash
flutter pub get
```

**Comment by mendoxe** [comment]
Can we merge this please?

**Comment by mertguner** [comment]
Fixed
